name: "Generate SAS token action"
description: "Generate SAS token"

inputs:
  storageaccount:
    description: "Storage Account to create a SAS token for"
    type: string
    required: true
  fileshare:
    description: "Fileshare to create a SAS token for"
    type: string
    required: true
    
runs:
  using: "composite"
  steps:    
    - name: Generate SAS token
      run: |
        # end=`date -u -d "24 hours" '+%Y-%m-%dT%H:%MZ'`
        # sasToken=$(az storage account generate-sas \
        #   --permissions cdlruwap \
        #   --account-name "${{ inputs.storageaccount }}" \
        #   --services f \
        #   --resource-types sco \
        #   --expiry $end \
        #   --https-only \
        #   -o tsv) 

        end=`date -u -d "3 minutes" '+%Y-%m-%dT%H:%MZ'`
        sasToken=$(az storage account generate-sas \
          --permissions cdlruwap \
          --account-name "${{ inputs.storageaccount }}" \
          --services f \
          --resource-types sco \
          --expiry $end \
          --https-only \
          -o tsv) 

        # masks all output of sasToken
        echo "::add-mask::${sasToken}"

        echo "STORAGE_SAS_TOKEN=${sasToken}" >> $GITHUB_ENV
        echo "FILESHARE=dev" >> $GITHUB_ENV


    - name: output SAS token
      run: |
        # SAS values
        echo "=========================================================================================================================================================="
        echo "| Variable   | Value       |"
        echo "| ---------- | ----------- |"
        echo "| SAS token  | ?${{ env.STORAGE_SAS_TOKEN }} |"
        echo "| File service SAS URL | https://${{ inputs.storageaccount }}.file.core.windows.net/?${{ env.STORAGE_SAS_TOKEN }} |"
        echo "| Fileshare SAS URL | https://${{ inputs.storageaccount }}.file.core.windows.net/${{ env.FILESHARE }}?${{ env.STORAGE_SAS_TOKEN }} |"
        echo "| Fileshare SAS URL | https://${{ inputs.storageaccount }}.file.core.windows.net/${{ inputs.fileshare }}?${{ env.STORAGE_SAS_TOKEN }} |"
        echo "=========================================================================================================================================================="
        
        {
          echo "### Workflow variables"
          echo "| Variable   | Value       |"
          echo "| ---------- | ----------- |"
          echo "| SAS token  | ?${{ env.STORAGE_SAS_TOKEN }} |"
          echo "| File service SAS URL | https://${{ inputs.storageaccount }}.file.core.windows.net/?${{ env.STORAGE_SAS_TOKEN }} |"
          echo "| Fileshare SAS URL | https://${{ inputs.storageaccount }}.file.core.windows.net/${{env.FILESHARE}}?${{ env.STORAGE_SAS_TOKEN }} |"
          echo "| Fileshare SAS URL | https://${{ inputs.storageaccount }}.file.core.windows.net/${{ inputs.fileshare }}?${{ env.STORAGE_SAS_TOKEN }} |"
        } >> $GITHUB_STEP_SUMMARY

