on:
  workflow_dispatch:
    inputs:
      location:
        description: "Hub Location (weu / frc)"
        type: choice
        required: true
        options:
          - 'weu'
          - 'frc'
      tenant:
        description: "GitHub tenant to deploy to (AE / MVP1)"
        type: string
        required: true
        options:
         - 'AE'
         - 'PROD'
      terraform-action:
        description: 'Terraform action'
        type: choice
        required: true
        options:
          - 'plan'
          - 'plan+apply'
          - 'destroy'
      confirm-destroy:
        description: "Confirm destroy"
        type: boolean
        default: false

name: Resource-group test

jobs:
  Resource-group-test:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      location: ${{ github.event.inputs.location }}
      tenant: ${{ github.event.inputs.tenant }}
      confirm-destroy: ${{ github.event.inputs.confirm-destroy }}
      terraform-action: ${{ github.event.inputs.terraform-action }}
      terraform-directory: 'rg-test'
      terraform-init-args: '-backend-config="key=reg.tfstate"'
      terraform-plan-args: '-var-file=test.tfvars'
      terraform-apply-args: '-var-file=test.tfvars'
    secrets: inherit