on:
  workflow_dispatch:
    inputs:
      location:
        description: "Hub Location (weu / frc)"
        type: choice
        required: true
        options:
          - 'weu'
          - 'frc'
      terraform-action:
        description: 'Terraform action'
        type: choice
        required: true
        options:
          - 'plan'
          - 'plan+apply'
          - 'destroy'
      confirm-destroy:
        description: "Confirm destroy"
        type: boolean
        default: false
      IsNewDeployment:
        description: "IsNewDeployment?"
        type: boolean
        default: false
        required: true

name: Vnet-peering test

jobs:
  Vnet-peering-test:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      location: ${{ github.event.inputs.location }}
      confirm-destroy: ${{ github.event.inputs.confirm-destroy }}
      IsNewDeployment: ${{ github.event.inputs.isNewDeployment }}
      terraform-action: ${{ github.event.inputs.terraform-action }}
      terraform-directory: 'peering'
      terraform-init-args: '-backend-config="key=vnet-peering.tfstate"'
      terraform-plan-args: ''
      terraform-apply-args: ''
    secrets: inherit