on:
  workflow_dispatch:
    inputs:
      location:
        description: "Hub Location (weu / frc)"
        type: choice
        required: true
        options:
          - 'weu'
          - 'frc'
      key:
        description: "key (weu / frc)"
        type: choice
        required: true
        options:
          - 'KEY'
          - 'KEY2'
      terraform-action:
        description: 'Terraform action'
        type: choice
        required: true
        options:
          - 'plan'
          - 'plan+apply'
          - 'destroy'
      confirm-destroy:
        description: "Confirm destroy"
        type: boolean
        default: false

name: Secret test

jobs:
  secret-test:
    uses: ./.github/workflows/deploy-secret-test-reusable.yml
    with:
      location: ${{ github.event.inputs.location }}
      confirm-destroy: ${{ github.event.inputs.confirm-destroy }}
      terraform-action: ${{ github.event.inputs.terraform-action }}
      terraform-directory: secret-in-reusable
      terraform-init-args: '-backend-config="key=secret-test.tfstate"'
      terraform-plan-args: ''
      terraform-apply-args: ''
    secrets: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      shared_key: ${{ github.event.inputs.Location == 'frc' && 'secrets.SECRET_KEY' || 'secrets.SECRET_KEY2' }}