on:
  workflow_dispatch:
    inputs:
      module_version:
        description: 'Module version'
        type: string
        required: true


name: "Fork Module version tag"
run-name: Fork Module version tag | Module version ${{ inputs.module_version }} 

jobs:
  validation:
    runs-on: ubuntu-latest
    environment: 'fakkel'
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: "v${{ inputs.module_version }}"


      -  name: Prepare module info
         id: prepare_module_info
         run: |
          echo "module_version=$(grep -h -E "(module_version)\s+=" info.tf | awk -F '=' '{print $2}' | tr -d '" ')" >> $GITHUB_OUTPUT
          echo $module_version

      - if: always()
        name: Echo - debug
        run: |
          echo "debug"
          
          if [[ ${{ steps.prepare_module_info.outputs.module_version }} == $(echo ${{ inputs.module_version }} | sed 's/v//g') ]]
          then
            echo "Module version in 'info.tf' matches with module version in Release Tag. Continue..."
          else
            echo "Module version in 'info.tf' (${{ inputs.module_version }}) does not match with module version in Release Tag ($(echo ${{ steps.prepare_module_info.outputs.module_version }} | sed 's/v//g')). Aborted!"
            exit 2
          fi 