name: "Remove Automation Account"

on: workflow_dispatch

jobs:
  terraform-rg:
    name: "Remove Automation Account"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      #ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
      TF_CLI_ARGS_init: '-backend-config="key=aa.tfstate"'
    defaults:
      run:
        working-directory: aa-test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan Destroy
        run: terraform plan -destroy

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
      