on:
  workflow_call:
    inputs:
      location:
        description: "Hub Location (weu / frc)"
        type: string
        required: true
      tenant:
        description: "GitHub tenant to deploy to (ae / prod)"
        type: string
        default: 'ae'
      terraform-action:
        description: 'Terraform action'
        type: string
        required: true
      confirm-destroy:
        description: "Confirm distroy"
        type: string
        required: true
      terraform-directory:
        description: "Directory with Terraform files to apply"
        type: string
        required: true
      terraform-init-args:
        description: "args to set as TF_CLI_ARGS_init"
        type: string
        required: true
      terraform-plan-args:
        description: "args to set as TF_CLI_ARGS_plan"
        type: string
        default: ''
      terraform-apply-args:
        description: "args to set as TF_CLI_ARGS_apply"
        type: string
        default: ''
      terraform-import-file:
        description: "Name of the terraform import file. Use the statefile name without location (<statefileName>.ps1)"
        type: string
        default: ''
      IsNewDeployment:
        description: "Initial foundation deployment ...... (should be true during the initial deployment of both hubs (weu & frc). A second deployment is needed after the initial deployment has been done for each hub)"
        type: string
        default: 'false'

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    environment: 'fakkel'
  
    env:
      TF_CLI_ARGS_init: ${{ inputs.terraform-init-args }}
      TF_CLI_ARGS_plan: ${{ inputs.terraform-plan-args }}
      TF_CLI_ARGS_apply: ${{ inputs.terraform-apply-args }}
      TF_CLI_ARGS_destroy: ${{ inputs.terraform-apply-args }}
      TF_VAR_environment: ${{ inputs.environment }}
      TF_VAR_location_code: ${{ inputs.location }}
      TF_VAR_new_deployment: ${{ inputs.IsNewDeployment }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      # ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_NEW }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true
      VPN_SECRET: ${{ inputs.Location == 'weu' && secrets.SECRET_KEY || secrets.SECRET_KEY2 }}
  
    steps:
      - name: '${{ github.ref_name }} to ${{ github.event.inputs.location }} ${{ github.event.inputs.tenant }}'
        run: echo ""
        
      - name: Log inputs
        run: |
          echo "Running with the following input:"
          echo "${{ toJSON(inputs) }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: 'Az CLI login'
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID_NEW }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      # - name: 'Az CLI login'
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set workflow environment variables
        run: ./scripts/set-workflow-env-variables.sh ${{ inputs.tenant }} ${{ inputs.location }} ${{ inputs.IsNewDeployment }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: |
          terraform -chdir=${{inputs.terraform-directory}} fmt -check

      - name: Terraform Init
        id: init
        run: |
          terraform -chdir=${{inputs.terraform-directory}} init \
            -backend-config="resource_group_name=tfstatetestfakkel" \
            -backend-config="storage_account_name=tfstatetestfakkel"

      - name: Terraform Validate
        id: validate
        run: |
          terraform -chdir=${{ inputs.terraform-directory }} validate

      - name: Terraform Import
        if: inputs.terraform-action == 'import'
        id: terraform-import
        shell: pwsh
        run: |
          ./import/${{ inputs.terraform-import-file }}.ps1 `
            -subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} `
            -location ${{ inputs.location }} `
            -terraformdir ${{ inputs.terraform-directory }}

      - name: Terraform Plan
        id: plan
        if: inputs.terraform-action != 'import'
        # env:
        #   ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        #   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #   ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        #   ARM_USE_OIDC: true

        run: |
          terraform -chdir=${{ inputs.terraform-directory }} plan -detailed-exitcode
          # terraform -chdir=${{ inputs.terraform-directory }} plan -input=false -out=plan
          if [ $? -eq 0 ]; then
          echo "No changes, not applying"
          if [ $? -eq 1 ]; then
              echo "Terraform plan failed"
              exit 1
          if [ $? -eq 2 ]; then
              echo "Terraform apply needed"
          fi

      - name: Terraform Apply
        if: inputs.terraform-action == 'plan+apply'
        run: |
          terraform -chdir=${{ inputs.terraform-directory }} apply "plan"
          # -auto-approve -input=false

      - name: Terraform Destroy
        if: inputs.terraform-action == 'destroy' && inputs.confirm-destroy
        run: |
          terraform -chdir=${{ inputs.terraform-directory }} destroy -auto-approve -input=false
