on:
  workflow_dispatch:
    inputs:
      storageaccount:
        description: "The Storage Account to create a SAS token for."
        type: string
        default: 'fileshareazcopy66e4bd71'
      fileshare:
        description: "The Fileshare to create a SAS token for."
        type: string
        default: 'dev'
      password:
        description: "The Password to use for the SAS token zip file."
        type: string
        default: ''
      action:
        description: "The rights the SAS token should have."
        type: choice
        options:
          - 'read'
          - 'write'


name: Generate SAS token zip via custom action 
run-name: Generate SAS token | ${{ inputs.storageaccount }} | ${{ inputs.fileshare }} | ${{ inputs.password }}
          
permissions:
  id-token: write
  contents: read
  issues: write 

jobs:
  generate-sas-token:
    runs-on: ubuntu-latest
    environment: 'fakkel'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Mask password
        run: |
          PASSWORD=$(jq -r '.inputs.password' $GITHUB_EVENT_PATH)
          echo ::add-mask::$PASSWORD

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     
      - name: Generate SAS token
        uses: ./.github/actions/sas-token-generation-zip
        with:
          storageaccount: ${{ inputs.storageaccount }}
          fileshare: ${{ inputs.fileshare }}
          password: ${{ inputs.password }}
          action: ${{ inputs.action }}



