on:
  workflow_dispatch:
    inputs:
      storageaccount:
        description: "Storage Account to create a SAS token for"
        type: string
        default: 'fileshareazcopy66e4bd71'
      fileshare:
        description: "Fileshare to create a SAS token for"
        type: string
        default: 'dev'

name: Generate SAS token via custom action
run-name: Generate SAS token | ${{ inputs.storageaccount }} | ${{ inputs.fileshare }}
          
permissions:
  id-token: write
  contents: read
  issues: write 

jobs:
  generate-sas-token:
    runs-on: ubuntu-latest
    environment: 'fakkel'
  
    # env:
    #   ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    #   ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    #   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #   ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    #   ARM_USE_OIDC: true
  
    steps:
      - name: '${{ github.ref_name }} to ${{ github.event.inputs.location }} ${{ github.event.inputs.tenant }}'
        run: echo ""
        
      - name: Log inputs
        run: |
          echo "Running with the following input:"
          echo "${{ toJSON(inputs) }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     
      - name: Generate SAS token
        uses: ./.github/actions/sas-token-generation.yml@main
        with:
          storageaccount: ${{ inputs.storageaccount }}
          fileshare: ${{ inputs.fileshare }}



