name: 'Smoketest-in-progress'

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 'fakkel'

    env:
      TF_CLI_ARGS_plan: ${{ inputs.terraform-plan-args }}
      TF_CLI_ARGS_apply: ${{ inputs.terraform-apply-args }}
      TF_CLI_ARGS_destroy: ${{ inputs.terraform-apply-args }}
      TF_VAR_environment: ${{ inputs.environment }}
      TF_VAR_location_code: ${{ inputs.location }}
      TF_VAR_new_deployment: ${{ inputs.IsNewDeployment }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true
      VPN_SECRET: ${{ inputs.Location == 'weu' && secrets.SECRET_KEY || secrets.SECRET_KEY2 }}

    steps:
      - uses: actions/checkout@v3
        name: 'checkout'
        
      - run: ./scripts/chef.sh  
        shell: bash
        env:
          INPUT_SUBSCRIPTIONID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          INPUT_CLIENTID: ${{ secrets.AZURE_CLIENT_ID }}
          INPUT_TENANTID: ${{ secrets.AZURE_TENANT_ID }}
          INPUT_CLIENTSECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          INPUT_COMPLIANCE_TEST_PROFILE_URL: 'niks'

      - name: 'upload test results'
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-result-${{ github.run_number }}
          path: test.html