name: 'Smoketest-in-progress'

on: 
  workflow_dispatch:
    inputs:
      location:
        description: "Hub Location (weu / frc)"
        type: choice
        required: true
        options:
          - 'weu'
          - 'frc'
        default: 'weu'
      tenant:
        description: "GitHub tenant to deploy to (ae / prod)"
        type: choice
        required: true
        options:
         - 'ae'
         - 'prod'
        default: 'ae'
      terraform-action:
        description: 'Terraform action'
        type: choice
        required: true
        options:
          - 'plan'
          - 'plan+apply'
          - 'destroy'
        default: 'plan'
      confirm-destroy:
        description: "Confirm destroy"
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read


jobs:
  # kv-terraform:
  #   uses: ./.github/workflows/smoke-test-kv.yml
  #   with:
  #     location: 'weu'
  #     tenant: ${{ github.event.inputs.tenant }}
  #     confirm-destroy: ${{ github.event.inputs.confirm-destroy }}
  #     terraform-action: ${{ github.event.inputs.terraform-action }}
  #     terraform-directory: 'kv-test'
  #     terraform-init-args: '-backend-config="key=kv.tfstate"'
  #     terraform-plan-args: ''
  #     terraform-apply-args: ''
  #     terraform-import-file: ${{ inputs.terraform-import-file }}
  #   secrets: inherit

  Inspec-tests:
    # needs: kv-terraform
    runs-on: ubuntu-latest
    # environment: 'fakkel'
    environment: "${{ inputs.tenant }}_READ_ONLY"

    env:
      TF_CLI_ARGS_plan: ${{ inputs.terraform-plan-args }}
      TF_CLI_ARGS_apply: ${{ inputs.terraform-apply-args }}
      TF_CLI_ARGS_destroy: ${{ inputs.terraform-apply-args }}
      TF_VAR_environment: ${{ inputs.environment }}
      TF_VAR_location_code: ${{ inputs.location }}
      terraform-directory: 'kv-test'
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true
      VPN_SECRET: ${{ inputs.Location == 'weu' && secrets.SECRET_KEY || secrets.SECRET_KEY2 }}

    steps:
      - uses: actions/checkout@v3
        name: 'checkout'
        
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: |
          terraform -chdir=${{ env.terraform-directory }} init \
            -backend-config="key=kv.tfstate" \
            -backend-config="resource_group_name=tfstatetestfakkel" \
            -backend-config="storage_account_name=tfstatetestfakkel"

      - name: Gather TF output
        run: ./scripts/output.sh 
        shell: bash
        env:
          TERRAFORM_DIRECTORY: ${{ env.terraform-directory }}
          
      - name: Inspec tests
        run: ./scripts/chef.sh  
        # shell: bash
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          
      - name: 'upload test results'
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: inspec-test-result-${{ github.run_number }}
          path: '**_test.html'